name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.9
          # Added -v to print detailed logs and keep the server from timing out
          buildozer-cmd: buildozer -v android debug

      - name: Upload APK Download Link
        uses: actions/upload-artifact@v4
        with:
          name: HID-Controller-APK
          path: bin/*.apk
